# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = exercise2.o
LINKOBJ  = exercise2.o
LIBS     = -L"D:/uygulamalar/Dev-Cpp/MinGW64/lib" -L"D:/uygulamalar/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/uygulamalar/Dev-Cpp/MinGW64/include" -I"D:/uygulamalar/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/uygulamalar/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/uygulamalar/Dev-Cpp/MinGW64/include" -I"D:/uygulamalar/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/uygulamalar/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/uygulamalar/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

exercise2.o: exercise2.c
	$(CC) -c exercise2.c -o exercise2.o $(CFLAGS)
